### ISSUE TITLE
Doesn't work in a Non-admin account

### ISSUE THREAD

**Issue by demoncodemonkey** [TomChantler/Always-Admin-VS#1]
Hi Tom, hows it going?

I installed this for VS2015 on Win10, and it does work fine in my admin account. VS opens in admin mode without any dialogs or anything.

But most of my time is actually spent in a non-admin account and it doesn't work from there. Running the .VBS doesn't do anything.

Good work though and isn't it such a pain that workarounds like this are needed :(

Cheers
demoncodemonkey

**Comment by TomChantler** [comment]
Hi demoncodemonkey,

Thanks for the feedback. I'm glad it's generally working okay for you.

This behaviour is intentional. At the moment the scripts run Visual Studio as the currently logged-in user, so it's not possible to run with higher privileges than are available to that user. Also, the need to run VS is sometimes the only way devs can get permission to be a local administrator and we don't want to ruin that ;-)

Having said that, I have some ideas about running as an admin under a different account. I'll try to  make time to look into this over the next few days, after which I'll give you a shout.

Cheers :-)

**Comment by TomChantler** [comment]
I think it's time to close this issue as I don't think it's desirable to run VS as a different user (and I haven't spent any time looking at it).
